import esbuild from 'esbuild';
import process from 'node:process';
import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import { basename, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import builtins from 'builtin-modules';
import esbuildSvelte from 'esbuild-svelte';
import sveltePreprocess from 'svelte-preprocess';

const projectDir = dirname(fileURLToPath(import.meta.url));
const prod = process.argv.includes('production');
const manifest = JSON.parse(await readFile(resolve(projectDir, 'manifest.json'), 'utf8'));
const outputDir = prod ? projectDir : resolve(projectDir, '../developmentVault/.obsidian/plugins', manifest.id);

const writePluginAssets = {
	name: 'write-plugin-assets',
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length) return;
			await mkdir(outputDir, { recursive: true });
			for (const file of result.outputFiles) {
				const filename = basename(file.path) === 'main.css' ? 'styles.css' : basename(file.path);
				// esbuild-svelte's virtual CSS namespace includes an absolute checkout path.
				// Keep relative source labels so release CSS is identical in other checkouts.
				const contents = filename === 'styles.css'
					? file.text.replaceAll(`/* fakecss:${projectDir.replaceAll('\\', '/')}/`, '/* svelte:')
					: file.contents;
				await writeFile(resolve(outputDir, filename), contents);
			}
			if (!prod) {
				await copyFile(resolve(projectDir, 'manifest.json'), resolve(outputDir, 'manifest.json'));
			}
		});
	},
};

await esbuild.build({
	absWorkingDir: projectDir,
	banner: { js: '/* Generated by esbuild. Source: https://github.com/everydaymind/obsidian-advanced-new-tab */' },
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian', 'electron',
		'@codemirror/autocomplete', '@codemirror/collab', '@codemirror/commands',
		'@codemirror/language', '@codemirror/lint', '@codemirror/search',
		'@codemirror/state', '@codemirror/view',
		'@lezer/common', '@lezer/highlight', '@lezer/lr', ...builtins,
	],
	format: 'cjs',
	watch: !prod,
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	write: false,
	outfile: resolve(outputDir, 'main.js'),
	plugins: [
		esbuildSvelte({
			// Svelte 3 uses false for extracted CSS; Svelte 5 uses 'external'.
			compilerOptions: { css: false },
			preprocess: sveltePreprocess(),
		}),
		writePluginAssets,
	],
});
